package com.eventmanager.app.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Predefined color themes inspired by Material Design 3 dynamic colors
 * for devices that don't support dynamic color theming
 */
data class ColorTheme(
    val name: String,
    val displayName: String,
    val lightColors: ColorScheme,
    val darkColors: ColorScheme
)

/**
 * Helper data class for organizing light and dark color schemes
 */
data class ColorScheme(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val inversePrimary: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color
)

object ColorThemes {
    
    // Helper function to convert our ColorScheme to Material3 ColorScheme
    private fun ColorScheme.toMaterial3ColorScheme(): androidx.compose.material3.ColorScheme {
        return androidx.compose.material3.lightColorScheme(
            primary = this.primary,
            onPrimary = this.onPrimary,
            primaryContainer = this.primaryContainer,
            onPrimaryContainer = this.onPrimaryContainer,
            secondary = this.secondary,
            onSecondary = this.onSecondary,
            secondaryContainer = this.secondaryContainer,
            onSecondaryContainer = this.onSecondaryContainer,
            tertiary = this.tertiary,
            onTertiary = this.onTertiary,
            tertiaryContainer = this.tertiaryContainer,
            onTertiaryContainer = this.onTertiaryContainer,
            error = this.error,
            onError = this.onError,
            errorContainer = this.errorContainer,
            onErrorContainer = this.onErrorContainer,
            background = this.background,
            onBackground = this.onBackground,
            surface = this.surface,
            onSurface = this.onSurface,
            surfaceVariant = this.surfaceVariant,
            onSurfaceVariant = this.onSurfaceVariant,
            outline = this.outline,
            outlineVariant = this.outlineVariant,
            scrim = this.scrim,
            inverseSurface = this.inverseSurface,
            inverseOnSurface = this.inverseOnSurface,
            inversePrimary = this.inversePrimary
        )
    }
    
    // System colors (default) - uses Material Design 3 dynamic colors
    val SYSTEM = ColorTheme(
        name = "system",
        displayName = "System Colors",
        lightColors = ColorScheme(
            primary = Color(0xFF6750A4),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFEADDFF),
            onPrimaryContainer = Color(0xFF21005D),
            secondary = Color(0xFF625B71),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFE8DEF8),
            onSecondaryContainer = Color(0xFF1D192B),
            tertiary = Color(0xFF7D5260),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFD8E4),
            onTertiaryContainer = Color(0xFF31111D),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFFFFBFE),
            onBackground = Color(0xFF1C1B1F),
            surface = Color(0xFFFFFBFE),
            onSurface = Color(0xFF1C1B1F),
            surfaceVariant = Color(0xFFE7E0EC),
            onSurfaceVariant = Color(0xFF49454F),
            outline = Color(0xFF79747E),
            outlineVariant = Color(0xFFCAC4D0),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF313033),
            inverseOnSurface = Color(0xFFF4EFF4),
            inversePrimary = Color(0xFFD0BCFF),
            surfaceDim = Color(0xFFDDD8DD),
            surfaceBright = Color(0xFFFFFBFE),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF7F2FA),
            surfaceContainer = Color(0xFFF1ECF4),
            surfaceContainerHigh = Color(0xFFEBE6ED),
            surfaceContainerHighest = Color(0xFFE6E0E9)
        ),
        darkColors = ColorScheme(
            primary = Color(0xFFD0BCFF),
            onPrimary = Color(0xFF381E72),
            primaryContainer = Color(0xFF4F378B),
            onPrimaryContainer = Color(0xFFEADDFF),
            secondary = Color(0xFFCCC2DC),
            onSecondary = Color(0xFF332D41),
            secondaryContainer = Color(0xFF4A4458),
            onSecondaryContainer = Color(0xFFE8DEF8),
            tertiary = Color(0xFFEFB8C8),
            onTertiary = Color(0xFF492532),
            tertiaryContainer = Color(0xFF633B48),
            onTertiaryContainer = Color(0xFFFFD8E4),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF1C1B1F),
            onBackground = Color(0xFFE6E1E5),
            surface = Color(0xFF1C1B1F),
            onSurface = Color(0xFFE6E1E5),
            surfaceVariant = Color(0xFF49454F),
            onSurfaceVariant = Color(0xFFCAC4D0),
            outline = Color(0xFF938F99),
            outlineVariant = Color(0xFF49454F),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFE6E1E5),
            inverseOnSurface = Color(0xFF313033),
            inversePrimary = Color(0xFF6750A4),
            surfaceDim = Color(0xFF141218),
            surfaceBright = Color(0xFF3B383E),
            surfaceContainerLowest = Color(0xFF0F0D13),
            surfaceContainerLow = Color(0xFF211F26),
            surfaceContainer = Color(0xFF25232A),
            surfaceContainerHigh = Color(0xFF2F2D35),
            surfaceContainerHighest = Color(0xFF3A383F)
        )
    )
    
    // Professional Blue theme - neutral and high contrast
    val PROFESSIONAL_BLUE = ColorTheme(
        name = "professional_blue",
        displayName = "Professional Blue",
        lightColors = ColorScheme(
            primary = Color(0xFF1E3A8A),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFDBEAFE),
            onPrimaryContainer = Color(0xFF1E40AF),
            secondary = Color(0xFF374151),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFF3F4F6),
            onSecondaryContainer = Color(0xFF1F2937),
            tertiary = Color(0xFF059669),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFD1FAE5),
            onTertiaryContainer = Color(0xFF047857),
            error = Color(0xFFDC2626),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFEE2E2),
            onErrorContainer = Color(0xFFB91C1C),
            background = Color(0xFFFFFFFF),
            onBackground = Color(0xFF111827),
            surface = Color(0xFFFFFFFF),
            onSurface = Color(0xFF111827),
            surfaceVariant = Color(0xFFF9FAFB),
            onSurfaceVariant = Color(0xFF374151),
            outline = Color(0xFF6B7280),
            outlineVariant = Color(0xFFE5E7EB),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF1F2937),
            inverseOnSurface = Color(0xFFF9FAFB),
            inversePrimary = Color(0xFF93C5FD),
            surfaceDim = Color(0xFFF3F4F6),
            surfaceBright = Color(0xFFFFFFFF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF9FAFB),
            surfaceContainer = Color(0xFFF3F4F6),
            surfaceContainerHigh = Color(0xFFE5E7EB),
            surfaceContainerHighest = Color(0xFFD1D5DB)
        ),
        darkColors = ColorScheme(
            primary = Color(0xFF93C5FD),
            onPrimary = Color(0xFF1E40AF),
            primaryContainer = Color(0xFF1E3A8A),
            onPrimaryContainer = Color(0xFFDBEAFE),
            secondary = Color(0xFFD1D5DB),
            onSecondary = Color(0xFF1F2937),
            secondaryContainer = Color(0xFF374151),
            onSecondaryContainer = Color(0xFFF3F4F6),
            tertiary = Color(0xFF86EFAC),
            onTertiary = Color(0xFF047857),
            tertiaryContainer = Color(0xFF059669),
            onTertiaryContainer = Color(0xFFD1FAE5),
            error = Color(0xFFFCA5A5),
            onError = Color(0xFFB91C1C),
            errorContainer = Color(0xFFDC2626),
            onErrorContainer = Color(0xFFFEE2E2),
            background = Color(0xFF111827),
            onBackground = Color(0xFFF9FAFB),
            surface = Color(0xFF111827),
            onSurface = Color(0xFFF9FAFB),
            surfaceVariant = Color(0xFF374151),
            onSurfaceVariant = Color(0xFFD1D5DB),
            outline = Color(0xFF9CA3AF),
            outlineVariant = Color(0xFF374151),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFF9FAFB),
            inverseOnSurface = Color(0xFF1F2937),
            inversePrimary = Color(0xFF1E3A8A),
            surfaceDim = Color(0xFF0F172A),
            surfaceBright = Color(0xFF1F2937),
            surfaceContainerLowest = Color(0xFF0C1220),
            surfaceContainerLow = Color(0xFF1E293B),
            surfaceContainer = Color(0xFF334155),
            surfaceContainerHigh = Color(0xFF475569),
            surfaceContainerHighest = Color(0xFF64748B)
        )
    )
    
    // Neutral Green theme - professional and readable
    val NEUTRAL_GREEN = ColorTheme(
        name = "neutral_green",
        displayName = "Neutral Green",
        lightColors = ColorScheme(
            primary = Color(0xFF166534),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFDCFCE7),
            onPrimaryContainer = Color(0xFF14532D),
            secondary = Color(0xFF374151),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFF3F4F6),
            onSecondaryContainer = Color(0xFF1F2937),
            tertiary = Color(0xFF7C3AED),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFEDE9FE),
            onTertiaryContainer = Color(0xFF6D28D9),
            error = Color(0xFFDC2626),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFEE2E2),
            onErrorContainer = Color(0xFFB91C1C),
            background = Color(0xFFFFFFFF),
            onBackground = Color(0xFF111827),
            surface = Color(0xFFFFFFFF),
            onSurface = Color(0xFF111827),
            surfaceVariant = Color(0xFFF9FAFB),
            onSurfaceVariant = Color(0xFF374151),
            outline = Color(0xFF6B7280),
            outlineVariant = Color(0xFFE5E7EB),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF1F2937),
            inverseOnSurface = Color(0xFFF9FAFB),
            inversePrimary = Color(0xFF86EFAC),
            surfaceDim = Color(0xFFF3F4F6),
            surfaceBright = Color(0xFFFFFFFF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF9FAFB),
            surfaceContainer = Color(0xFFF3F4F6),
            surfaceContainerHigh = Color(0xFFE5E7EB),
            surfaceContainerHighest = Color(0xFFD1D5DB)
        ),
        darkColors = ColorScheme(
            primary = Color(0xFF86EFAC),
            onPrimary = Color(0xFF14532D),
            primaryContainer = Color(0xFF166534),
            onPrimaryContainer = Color(0xFFDCFCE7),
            secondary = Color(0xFFD1D5DB),
            onSecondary = Color(0xFF1F2937),
            secondaryContainer = Color(0xFF374151),
            onSecondaryContainer = Color(0xFFF3F4F6),
            tertiary = Color(0xFFC4B5FD),
            onTertiary = Color(0xFF6D28D9),
            tertiaryContainer = Color(0xFF7C3AED),
            onTertiaryContainer = Color(0xFFEDE9FE),
            error = Color(0xFFFCA5A5),
            onError = Color(0xFFB91C1C),
            errorContainer = Color(0xFFDC2626),
            onErrorContainer = Color(0xFFFEE2E2),
            background = Color(0xFF111827),
            onBackground = Color(0xFFF9FAFB),
            surface = Color(0xFF111827),
            onSurface = Color(0xFFF9FAFB),
            surfaceVariant = Color(0xFF374151),
            onSurfaceVariant = Color(0xFFD1D5DB),
            outline = Color(0xFF9CA3AF),
            outlineVariant = Color(0xFF374151),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFF9FAFB),
            inverseOnSurface = Color(0xFF1F2937),
            inversePrimary = Color(0xFF166534),
            surfaceDim = Color(0xFF0F172A),
            surfaceBright = Color(0xFF1F2937),
            surfaceContainerLowest = Color(0xFF0C1220),
            surfaceContainerLow = Color(0xFF1E293B),
            surfaceContainer = Color(0xFF334155),
            surfaceContainerHigh = Color(0xFF475569),
            surfaceContainerHighest = Color(0xFF64748B)
        )
    )
    
    // Warm Gray theme - neutral and professional
    val WARM_GRAY = ColorTheme(
        name = "warm_gray",
        displayName = "Warm Gray",
        lightColors = ColorScheme(
            primary = Color(0xFF4B5563),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFE5E7EB),
            onPrimaryContainer = Color(0xFF374151),
            secondary = Color(0xFF374151),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFF3F4F6),
            onSecondaryContainer = Color(0xFF1F2937),
            tertiary = Color(0xFF059669),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFD1FAE5),
            onTertiaryContainer = Color(0xFF047857),
            error = Color(0xFFDC2626),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFEE2E2),
            onErrorContainer = Color(0xFFB91C1C),
            background = Color(0xFFFFFFFF),
            onBackground = Color(0xFF111827),
            surface = Color(0xFFFFFFFF),
            onSurface = Color(0xFF111827),
            surfaceVariant = Color(0xFFF9FAFB),
            onSurfaceVariant = Color(0xFF374151),
            outline = Color(0xFF6B7280),
            outlineVariant = Color(0xFFE5E7EB),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF1F2937),
            inverseOnSurface = Color(0xFFF9FAFB),
            inversePrimary = Color(0xFF9CA3AF),
            surfaceDim = Color(0xFFF3F4F6),
            surfaceBright = Color(0xFFFFFFFF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF9FAFB),
            surfaceContainer = Color(0xFFF3F4F6),
            surfaceContainerHigh = Color(0xFFE5E7EB),
            surfaceContainerHighest = Color(0xFFD1D5DB)
        ),
        darkColors = ColorScheme(
            primary = Color(0xFF9CA3AF),
            onPrimary = Color(0xFF374151),
            primaryContainer = Color(0xFF4B5563),
            onPrimaryContainer = Color(0xFFE5E7EB),
            secondary = Color(0xFFD1D5DB),
            onSecondary = Color(0xFF1F2937),
            secondaryContainer = Color(0xFF374151),
            onSecondaryContainer = Color(0xFFF3F4F6),
            tertiary = Color(0xFF86EFAC),
            onTertiary = Color(0xFF047857),
            tertiaryContainer = Color(0xFF059669),
            onTertiaryContainer = Color(0xFFD1FAE5),
            error = Color(0xFFFCA5A5),
            onError = Color(0xFFB91C1C),
            errorContainer = Color(0xFFDC2626),
            onErrorContainer = Color(0xFFFEE2E2),
            background = Color(0xFF111827),
            onBackground = Color(0xFFF9FAFB),
            surface = Color(0xFF111827),
            onSurface = Color(0xFFF9FAFB),
            surfaceVariant = Color(0xFF374151),
            onSurfaceVariant = Color(0xFFD1D5DB),
            outline = Color(0xFF9CA3AF),
            outlineVariant = Color(0xFF374151),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFF9FAFB),
            inverseOnSurface = Color(0xFF1F2937),
            inversePrimary = Color(0xFF4B5563),
            surfaceDim = Color(0xFF0F172A),
            surfaceBright = Color(0xFF1F2937),
            surfaceContainerLowest = Color(0xFF0C1220),
            surfaceContainerLow = Color(0xFF1E293B),
            surfaceContainer = Color(0xFF334155),
            surfaceContainerHigh = Color(0xFF475569),
            surfaceContainerHighest = Color(0xFF64748B)
        )
    )
    
    // Neutral Purple theme - professional and readable
    val NEUTRAL_PURPLE = ColorTheme(
        name = "neutral_purple",
        displayName = "Neutral Purple",
        lightColors = ColorScheme(
            primary = Color(0xFF7C3AED),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFEDE9FE),
            onPrimaryContainer = Color(0xFF6D28D9),
            secondary = Color(0xFF374151),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFF3F4F6),
            onSecondaryContainer = Color(0xFF1F2937),
            tertiary = Color(0xFF059669),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFD1FAE5),
            onTertiaryContainer = Color(0xFF047857),
            error = Color(0xFFDC2626),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFEE2E2),
            onErrorContainer = Color(0xFFB91C1C),
            background = Color(0xFFFFFFFF),
            onBackground = Color(0xFF111827),
            surface = Color(0xFFFFFFFF),
            onSurface = Color(0xFF111827),
            surfaceVariant = Color(0xFFF9FAFB),
            onSurfaceVariant = Color(0xFF374151),
            outline = Color(0xFF6B7280),
            outlineVariant = Color(0xFFE5E7EB),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF1F2937),
            inverseOnSurface = Color(0xFFF9FAFB),
            inversePrimary = Color(0xFFC4B5FD),
            surfaceDim = Color(0xFFF3F4F6),
            surfaceBright = Color(0xFFFFFFFF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF9FAFB),
            surfaceContainer = Color(0xFFF3F4F6),
            surfaceContainerHigh = Color(0xFFE5E7EB),
            surfaceContainerHighest = Color(0xFFD1D5DB)
        ),
        darkColors = ColorScheme(
            primary = Color(0xFFC4B5FD),
            onPrimary = Color(0xFF6D28D9),
            primaryContainer = Color(0xFF7C3AED),
            onPrimaryContainer = Color(0xFFEDE9FE),
            secondary = Color(0xFFD1D5DB),
            onSecondary = Color(0xFF1F2937),
            secondaryContainer = Color(0xFF374151),
            onSecondaryContainer = Color(0xFFF3F4F6),
            tertiary = Color(0xFF86EFAC),
            onTertiary = Color(0xFF047857),
            tertiaryContainer = Color(0xFF059669),
            onTertiaryContainer = Color(0xFFD1FAE5),
            error = Color(0xFFFCA5A5),
            onError = Color(0xFFB91C1C),
            errorContainer = Color(0xFFDC2626),
            onErrorContainer = Color(0xFFFEE2E2),
            background = Color(0xFF111827),
            onBackground = Color(0xFFF9FAFB),
            surface = Color(0xFF111827),
            onSurface = Color(0xFFF9FAFB),
            surfaceVariant = Color(0xFF374151),
            onSurfaceVariant = Color(0xFFD1D5DB),
            outline = Color(0xFF9CA3AF),
            outlineVariant = Color(0xFF374151),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFF9FAFB),
            inverseOnSurface = Color(0xFF1F2937),
            inversePrimary = Color(0xFF7C3AED),
            surfaceDim = Color(0xFF0F172A),
            surfaceBright = Color(0xFF1F2937),
            surfaceContainerLowest = Color(0xFF0C1220),
            surfaceContainerLow = Color(0xFF1E293B),
            surfaceContainer = Color(0xFF334155),
            surfaceContainerHigh = Color(0xFF475569),
            surfaceContainerHighest = Color(0xFF64748B)
        )
    )
    
    // Rich Brown theme - inspired by the image, warm and professional
    val RICH_BROWN = ColorTheme(
        name = "rich_brown",
        displayName = "Rich Brown",
        lightColors = ColorScheme(
            primary = Color(0xFF4A3F35),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFF5F0E6),
            onPrimaryContainer = Color(0xFF4A3F35),
            secondary = Color(0xFF4A3F35),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFF5F0E6),
            onSecondaryContainer = Color(0xFF4A3F35),
            tertiary = Color(0xFF059669),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFD1FAE5),
            onTertiaryContainer = Color(0xFF047857),
            error = Color(0xFFDC2626),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFEE2E2),
            onErrorContainer = Color(0xFFB91C1C),
            background = Color(0xFFF5F0E6),
            onBackground = Color(0xFF4A3F35),
            surface = Color(0xFFF5F0E6),
            onSurface = Color(0xFF4A3F35),
            surfaceVariant = Color(0xFFE0D8CC),
            onSurfaceVariant = Color(0xFF4A3F35),
            outline = Color(0xFF4A3F35),
            outlineVariant = Color(0xFFD1C7B8),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF4A3F35),
            inverseOnSurface = Color(0xFFF5F0E6),
            inversePrimary = Color(0xFF8D7B6F),
            surfaceDim = Color(0xFFE0D8CC),
            surfaceBright = Color(0xFFF5F0E6),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF5F0E6),
            surfaceContainer = Color(0xFFE0D8CC),
            surfaceContainerHigh = Color(0xFFD1C7B8),
            surfaceContainerHighest = Color(0xFFC4B5A3)
        ),
        darkColors = ColorScheme(
            primary = Color(0xFFD1C7B8),
            onPrimary = Color(0xFF2D2520),
            primaryContainer = Color(0xFF4A3F35),
            onPrimaryContainer = Color(0xFFF5F0E6),
            secondary = Color(0xFFD1C7B8),
            onSecondary = Color(0xFF2D2520),
            secondaryContainer = Color(0xFF4A3F35),
            onSecondaryContainer = Color(0xFFF5F0E6),
            tertiary = Color(0xFF86EFAC),
            onTertiary = Color(0xFF047857),
            tertiaryContainer = Color(0xFF059669),
            onTertiaryContainer = Color(0xFFD1FAE5),
            error = Color(0xFFFCA5A5),
            onError = Color(0xFFB91C1C),
            errorContainer = Color(0xFFDC2626),
            onErrorContainer = Color(0xFFFEE2E2),
            background = Color(0xFF1A1612),
            onBackground = Color(0xFFE0D8CC),
            surface = Color(0xFF1A1612),
            onSurface = Color(0xFFE0D8CC),
            surfaceVariant = Color(0xFF4A3F35),
            onSurfaceVariant = Color(0xFFD1C7B8),
            outline = Color(0xFF8D7B6F),
            outlineVariant = Color(0xFF4A3F35),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFE0D8CC),
            inverseOnSurface = Color(0xFF2D2520),
            inversePrimary = Color(0xFF4A3F35),
            surfaceDim = Color(0xFF0F0C09),
            surfaceBright = Color(0xFF2D2520),
            surfaceContainerLowest = Color(0xFF0A0806),
            surfaceContainerLow = Color(0xFF1A1612),
            surfaceContainer = Color(0xFF4A3F35),
            surfaceContainerHigh = Color(0xFF5A4F45),
            surfaceContainerHighest = Color(0xFF6B5F55)
        )
    )
    
    // Feminist Violet theme - empowering and vibrant (International Women's Day)
    val FEMINIST_VIOLET = ColorTheme(
        name = "feminist_violet",
        displayName = "Feminist Violet",
        lightColors = ColorScheme(
            primary = Color(0xFF9333EA), // Deep Violet
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFF3E8FF), // Light Violet
            onPrimaryContainer = Color(0xFF6B21A8),
            secondary = Color(0xFFEA580C), // Warm Orange for accent
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFEEDE2),
            onSecondaryContainer = Color(0xFFC2410C),
            tertiary = Color(0xFF059669), // Green for balance
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFD1FAE5),
            onTertiaryContainer = Color(0xFF047857),
            error = Color(0xFFDC2626),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFEE2E2),
            onErrorContainer = Color(0xFFB91C1C),
            background = Color(0xFFFAF5FF), // Very light violet tint
            onBackground = Color(0xFF2D1B4E),
            surface = Color(0xFFFAF5FF),
            onSurface = Color(0xFF2D1B4E),
            surfaceVariant = Color(0xFFEDE9FE), // Soft violet
            onSurfaceVariant = Color(0xFF6B5A8E),
            outline = Color(0xFF9378A3),
            outlineVariant = Color(0xFFDDD5E9),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF3D2A5C),
            inverseOnSurface = Color(0xFFF5EFFF),
            inversePrimary = Color(0xFFE9D5FF),
            surfaceDim = Color(0xFFEDE9FE),
            surfaceBright = Color(0xFFFAF5FF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF5F0FF),
            surfaceContainer = Color(0xFFEDE9FE),
            surfaceContainerHigh = Color(0xFFE4DCFF),
            surfaceContainerHighest = Color(0xFFDBCFFF)
        ),
        darkColors = ColorScheme(
            primary = Color(0xFFE9D5FF), // Light Violet for dark mode
            onPrimary = Color(0xFF6B21A8),
            primaryContainer = Color(0xFF9333EA),
            onPrimaryContainer = Color(0xFFF3E8FF),
            secondary = Color(0xFFFFB88C), // Light Orange
            onSecondary = Color(0xFF7A2E0F),
            secondaryContainer = Color(0xFFA84C1A),
            onSecondaryContainer = Color(0xFFFEEDE2),
            tertiary = Color(0xFF86EFAC), // Light Green
            onTertiary = Color(0xFF047857),
            tertiaryContainer = Color(0xFF059669),
            onTertiaryContainer = Color(0xFFD1FAE5),
            error = Color(0xFFFCA5A5),
            onError = Color(0xFFB91C1C),
            errorContainer = Color(0xFFDC2626),
            onErrorContainer = Color(0xFFFEE2E2),
            background = Color(0xFF1F0E3D), // Dark violet
            onBackground = Color(0xFFF5EFFF),
            surface = Color(0xFF1F0E3D),
            onSurface = Color(0xFFF5EFFF),
            surfaceVariant = Color(0xFF49354F),
            onSurfaceVariant = Color(0xFFDDD5E9),
            outline = Color(0xFFA899B3),
            outlineVariant = Color(0xFF49354F),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFF5EFFF),
            inverseOnSurface = Color(0xFF2D1B4E),
            inversePrimary = Color(0xFF9333EA),
            surfaceDim = Color(0xFF140927),
            surfaceBright = Color(0xFF3D2A5C),
            surfaceContainerLowest = Color(0xFF0F0619),
            surfaceContainerLow = Color(0xFF281748),
            surfaceContainer = Color(0xFF331B5C),
            surfaceContainerHigh = Color(0xFF3E2570),
            surfaceContainerHighest = Color(0xFF4A3185)
        )
    )
    
    // All available themes
    val allThemes = listOf(
        SYSTEM,
        PROFESSIONAL_BLUE,
        NEUTRAL_GREEN,
        WARM_GRAY,
        NEUTRAL_PURPLE,
        RICH_BROWN,
        FEMINIST_VIOLET
    )
    
    fun getThemeByName(name: String): ColorTheme {
        return allThemes.find { it.name == name } ?: SYSTEM
    }
}
